# Setup
title:               Jake Drew
tagline:             'Oxford | Swansea'
description:         ''
github_username:     jakedrew
url:                 https://jakedrw.com/
baseurl:             ''

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - projects.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
