# Setup
title:               Jake Drew
tagline:             ''
description:         ''
url:                 https://jakedrew.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jake Drew
  url:               https://twitter.com/jakedrw
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
